name: fast_crm
description: "Projet de gestion de client (L3 - GI)" #j'ai mis une bonne description
publish_to: 'none' 

environment:
  sdk: ^3.0.0 # J'ai élargi la compatibilité pour éviter des erreurs de version SDK

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  crypto: ^3.0.3
  url_launcher: ^6.2.4  # Pour ouvrir Téléphone et Mail
  local_auth: ^2.1.8    # Pour l'empreinte digitale
  shared_preferences: ^2.2.2

  # Icônes style iOS (standard Flutter)
  cupertino_icons: ^1.0.8
  
  # Librairie pour les graphiques (le camembert)
  fl_chart: ^1.1.0

dependency_overrides:
  vector_math: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Déclaration des images
  assets:
    - assets/